# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VSIXVERSION: 1.0.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required by MinVer to determine the version correctly
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3        
        
    - name: Restore dependencies
      run: dotnet restore src/EntityFrameworkRuler.sln --v:m
      
      
    - name: Test Build
      run: dotnet build EntityFrameworkRuler.sln --configuration Debug --no-restore --v:q
      # run: msbuild EntityFrameworkRuler.sln /property:Configuration=Debug /t:Rebuild /p:RestorePackages=false /consoleloggerparameters:ErrorsOnly -m
      working-directory: src      
      
    - name: Test Design
      run: dotnet test ./src/Tests/EntityFrameworkRuler.Design.Tests --no-build --v:m
    - name: Test CLI
      run: dotnet test ./src/Tests/EntityFrameworkRuler.Tests --no-build --v:m
        
    - name: Remove nupkg folder
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./nupkg
        
    - name: Release Build
      run: dotnet build .\src\EntityFrameworkRuler.sln --configuration Release --no-restore --v:q
      # run: msbuild EntityFrameworkRuler.sln /property:Configuration=Release /t:Rebuild /p:RestorePackages=false /consoleloggerparameters:ErrorsOnly -m
 
    
    - name: Create NuGet packages
      run: dotnet pack --configuration Release --no-build --no-restore .\src\EntityFrameworkRuler.sln --output .\nupkg 
      
#    - name: Publish Common package to NuGet 
#      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }}
#      working-directory: nupkg
 
    - name: Set VSIX Version ${{ env.VSIXVERSION }}
      uses: cezarypiatek/VsixVersionAction@1.0
      with:
        version: ${{ env.VSIXVERSION }}
        vsix-manifest-file: 'src\EntityFrameworkRuler.Vsix\source.extension.vsixmanifest'

    - name: Restore VSIX Project
      run: msbuild /t:restore EntityFrameworkRuler.Vsix.csproj
      working-directory: src/EntityFrameworkRuler.Vsix
      
    - name: Build VSIX ${{ env.VSIXVERSION }}
      run: msbuild EntityFrameworkRuler.sln /property:Configuration=ReleaseVsix /p:RestorePackages=True /p:DeployExtension=False /verbosity:minimal /consoleloggerparameters:ErrorsOnly -m
      working-directory: src
 
    - name: Move VSIX
      run: mv src/EntityFrameworkRuler.Vsix/bin/Release/EntityFrameworkRuler.Vsix.vsix EntityFrameworkRuler${{ env.VSIXVERSION }}.vsix
        
    - name: Publish VSIX ${{ env.VSIXVERSION }} artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Vsix-Artifacts
        path: |
          *.vsix
          docs/Vsix.md
          
      #https://github.com/marketplace/actions/vsix-publisher
    - name: Publish VSIX ${{ env.VSIXVERSION }} to Marketplace 
      uses: cezarypiatek/VsixPublisherAction@0.2
      with:
        extension-file: 'EntityFrameworkRuler${{ env.VSIXVERSION }}.vsix'
        publish-manifest-file: 'src\EntityFrameworkRuler.Vsix\PublishManifest.json'
        personal-access-code: ${{ secrets.VSIX_TOKEN }}      