# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3        
        
    - name: Restore dependencies
      run: dotnet restore src/EntityFrameworkRuler.sln
      
      
    - name: Test Build
      #run: dotnet build src/EntityFrameworkRuler.sln --configuration Debug --no-restore
      run: msbuild EntityFrameworkRuler.sln /property:Configuration=Debug /t:Rebuild /p:RestorePackages=false
      working-directory: src      
      
    - name: Test Design
      run: dotnet test ./src/Tests/EntityFrameworkRuler.Design.Tests --no-build --verbosity normal
    - name: Test CLI
      run: dotnet test ./src/Tests/EntityFrameworkRuler.Tests --no-build --verbosity normal
      
    - name: Remove EntityFrameworkRuler.Common/nupkg
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./src/EntityFrameworkRuler.Common/nupkg
        
    - name: Remove EntityFrameworkRuler/nupkg
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./src/EntityFrameworkRuler/nupkg
        
    - name: Remove EntityFrameworkRuler.Design/nupkg
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./src/EntityFrameworkRuler.Design/nupkg
        
    - name: Remove EntityFrameworkRuler.Editor/nupkg
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./src/EntityFrameworkRuler.Editor/nupkg
        
    - name: Release Build
      #run: dotnet build src/EntityFrameworkRuler.sln --configuration Release --no-restore
      run: msbuild EntityFrameworkRuler.sln /property:Configuration=Release /t:Rebuild /p:RestorePackages=false
      working-directory: src
    
    - name: Create NuGet package
      run: dotnet pack --configuration Release --no-build --no-restore src
    - name: Publish Common package to NuGet
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push --source https://api.nuget.org/v3/index.json ./src/EntityFrameworkRuler.Common/nupkg/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate
    - name: Publish CLI package to NuGet
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push --source https://api.nuget.org/v3/index.json ./src/EntityFrameworkRuler/nupkg/*.nupkg -k $NUGET_AUTH_TOKEN  --skip-duplicate      
    - name: Publish Design package to NuGet
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push --source https://api.nuget.org/v3/index.json ./src/EntityFrameworkRuler.Design/nupkg/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate      
    - name: Publish Editor package to NuGet
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push --source https://api.nuget.org/v3/index.json ./src/EntityFrameworkRuler.Editor/nupkg/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate      
        